apiVersion: azconfig.io/v1
kind: AzureAppConfigurationProvider
metadata:
  name: appconfigurationprovider-sample
spec:
  endpoint: https://appcs.azconfig.io
  target:
    configMapName: configmap-created-by-appconfig-provider
    configMapData: 
      type: default
    secret:
      target:
        secretName: COLOR
  auth:
    managedIdentityClientId: 2c8f6bf7-69be-486f-b80e-4fc32b4722a9