apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa
  annotations:
    azure.workload.identity/client-id: 2c8f6bf7-69be-486f-b80e-4fc32b4722a9
    azure.workload.identity/tenant-id: ab968060-1bea-4e12-ba68-c8579dd00e75