apiVersion: v1
kind: Service
metadata:
  name: appcs-service
  namespace: configmap4
spec:
  selector:
    app: appcs
  ports:
    - protocol: TCP
      port: 80  # Expose port 80
      targetPort: 80  # Target port for the application container
  type: LoadBalancer  # Expose service externally using a LoadBalancer (or use ClusterIP for internal access)
