apiVersion: v1
kind: Service
metadata:
  name: configmap-from-env-svc
spec:
  type: LoadBalancer
  selector:
    app: configmap-from-env
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
